### ISSUE TITLE
Make decoder callback based

### ISSUE THREAD

**Issue by rauchg** [Automattic/engine.io-protocol#7]
It should emit a callback with each packet:

```js
decodePayload(packetsString, function(packet, isLast){});
```

Callback arguments:
- `packet` just like each item of the returned array right now
- `isLast` `true` if it's the last packet in the payload, `false` otherwise.

Instead of returning an array like it is now.
This will give us the possibility of giving events to the user before all packets are parsed from the string (important for very big payloads).

Let's make sure to add tests for this.

**Comment by defunctzombie** [comment]
This is likely done when @rase- did the work for blobs.
